[package]
name = "web3-info"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
qdrant-client = "1.11.2"
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
