[tool.poetry]
name = "web3info"
version = "0.1.0"
description = ""
authors = ["adolf <adolf1321794021@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.50.2"
transformers = "^4.45.1"
seaborn = "^0.13.2"
ruff = "^0.6.8"
python-dotenv = "^1.0.1"
jinja2 = "^3.1.4"
pygments = "^2.18.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
